name: Docker Image Build & Push
description: Build Docker image and push to a container registry

inputs:
  registry-url:
    description: Docker container registry server URL
    required: true
  registry-username:
    description: Docker container registry username
    required: true
  registry-password:
    description: Docker container registry password
    required: true
  image-name:
    description: Docker image name
    required: true
  metadata-tags:
    description: List of tags as key-value pair attributes
    required: true
  metadata-labels:
    description: List of labels as key-value pair attributes
    required: false
  docker-context:
    description: Docker build's context
    required: false
  docker-file:
    description: Path to the Dockerfile
    required: false
  docker-args:
    description: List of build args as key-value pair attributes
    required: false

runs:
  using: composite
  steps:
  - name: Log in to Docker Container Registry
    # see https://github.com/docker/login-action/commit/f4ef78c080cd8ba55a85445d5b36e214a81df20a
    uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
    with:
      registry: ${{ inputs.registry-url }}
      username: ${{ inputs.registry-username }}
      password: ${{ inputs.registry-password }}

  - name: Extract metadata
    id: meta
    # see https://github.com/docker/metadata-action/commit/507c2f2dc502c992ad446e3d7a5dfbe311567a96
    uses: docker/metadata-action@f7b4ed12385588c3f9bc252f0a2b520d83b52d48
    with:
      images: ${{ inputs.registry-url }}/${{ inputs.image-name }}
      tags: ${{ inputs.metadata-tags }}
      labels: ${{ inputs.metadata-labels }}

  - name: Set up Docker Buildx
    # see https://github.com/docker/setup-buildx-action/commit/f03ac48505955848960e80bbb68046aa35c7b9e7
    uses: docker/setup-buildx-action@abe89fb761023d1d963c81f6b5e0df54236dc097

  - name: Set Environment variables
    run: |
      DOCKER_LAYERS_PATH="/tmp/.buildx-cache-${{ inputs.image-name }}"
      echo "DOCKER_LAYERS_PATH=${DOCKER_LAYERS_PATH}" >> $GITHUB_ENV
    shell: bash

    # see https://github.com/docker/build-push-action/issues/252#issuecomment-744400434
  - name: Cache Docker layers
    # see https://github.com/actions/cache/commit/69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
    uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
    with:
      path: ${{ env.DOCKER_LAYERS_PATH }}
      key: ${{ runner.os }}-buildx-${{ inputs.image-name }}-${{ github.sha }}
      restore-keys: ${{ runner.os }}-buildx-${{ inputs.image-name }}

  - name: Build and push Docker image
    # see https://github.com/docker/build-push-action/commit/3b5e8027fcad23fda98b2e3ac259d8d67585f671
    uses: docker/build-push-action@ef6cba335306ace1da064b44f9f739dec9be9fa0
    with:
      context: ${{ inputs.docker-context }}
      file: ${{ inputs.docker-file }}
      push: true
      provenance: false
      tags: ${{ steps.meta.outputs.tags }}
      build-args: ${{ inputs.docker-args }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=local,src=${{ env.DOCKER_LAYERS_PATH }}
      cache-to: type=local,dest=${{ env.DOCKER_LAYERS_PATH }}-new

  - name: Move Docker layers cache
    run: |
      rm -rf ${{ env.DOCKER_LAYERS_PATH }}
      mv ${{ env.DOCKER_LAYERS_PATH }}-new ${{ env.DOCKER_LAYERS_PATH }}
    shell: bash
