name: Docker Image Build & Push
description: Build Docker image and push to a container registry

inputs:
  registry-url:
    description: Docker container registry server URL
    required: true
  registry-username:
    description: Docker container registry username
    required: true
  registry-password:
    description: Docker container registry password
    required: true
  image-name:
    description: Docker image name
    required: true
  metadata-tags:
    description: List of tags as key-value pair attributes
    required: true
  metadata-labels:
    description: List of labels as key-value pair attributes
    required: false
  docker-context:
    description: Docker build's context
    required: false
  docker-file:
    description: Path to the Dockerfile
    required: false
  docker-args:
    description: List of build args as key-value pair attributes
    required: false
  docker-outputs:
    description: List of output destinations
    required: false
  trivy:
    description: Run Trivy vulnerability scanner
    required: false
    default: 'false'

outputs:
  docker-version:
    description: Generated Docker image version
    value: ${{ steps.delegate.outputs.docker-version }}
  docker-tags:
    description: Generated Docker tags
    value: ${{ steps.delegate.outputs.docker-tags }}
  docker-labels:
    description: Generated Docker labels
    value: ${{ steps.delegate.outputs.docker-labels }}
  docker-annotations:
    description: Generated annotations
    value: ${{ steps.delegate.outputs.docker-annotations }}
  metadata-json:
    description: JSON output of tags and labels
    value: ${{ steps.delegate.outputs.metadata-json }}
  bake-file-tags:
    description: Bake definition file with tags
    value: ${{ steps.delegate.outputs.bake-file-tags }}
  bake-file-labels:
    description: Bake definition file with labels
    value: ${{ steps.delegate.outputs.bake-file-labels }}
  bake-file-annotations:
    description: Bake definition file with annotations
    value: ${{ steps.delegate.outputs.bake-file-annotations }}
  bake-file:
    description: Bake definition file with tags and labels
    value: ${{ steps.delegate.outputs.bake-file }}

runs:
  using: composite
  steps:
  - id: delegate
    name: Delegate to docker-build-push
    uses: ./docker-build-push
    with:
      registry-url: ${{ inputs.registry-url }}
      registry-username: ${{ inputs.registry-username }}
      registry-password: ${{ inputs.registry-password }}
      image-name: ${{ inputs.image-name }}
      metadata-tags: ${{ inputs.metadata-tags }}
      metadata-labels: ${{ inputs.metadata-labels }}
      docker-context: ${{ inputs.docker-context }}
      docker-file: ${{ inputs.docker-file }}
      docker-args: ${{ inputs.docker-args }}
      docker-outputs: ${{ inputs.docker-outputs }}
      trivy: ${{ inputs.trivy }}
