name: Docker Image Build & Push
description: Build Docker image and push to a container registry

inputs:
  registry-url:
    description: Docker container registry server URL
    required: true
  registry-username:
    description: Docker container registry username
    required: true
  registry-password:
    description: Docker container registry password
    required: true
  image-name:
    description: Docker image name
    required: true
  metadata-tags:
    description: List of tags as key-value pair attributes
    required: true
  metadata-labels:
    description: List of labels as key-value pair attributes
    required: false
  docker-context:
    description: Docker build's context
    required: false
  docker-file:
    description: Path to the Dockerfile
    required: false
  docker-args:
    description: List of build args as key-value pair attributes
    required: false
  trivy:
    description: Run Trivy vulnerability scanner
    required: false
    default: 'false'

runs:
  using: composite
  steps:
  - name: Log in to Docker Container Registry
    # See https://github.com/docker/login-action/commits/master/
    uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
    with:
      registry: ${{ inputs.registry-url }}
      username: ${{ inputs.registry-username }}
      password: ${{ inputs.registry-password }}

  - name: Extract metadata
    id: meta
    # See https://github.com/docker/metadata-action/commits/master/
    uses: docker/metadata-action@b53be03109c4ef6f6cc7aa545b84b17a7fe51c1e
    with:
      images: ${{ inputs.registry-url }}/${{ inputs.image-name }}
      tags: ${{ inputs.metadata-tags }}
      labels: ${{ inputs.metadata-labels }}

  - name: Set up Docker Buildx
    # See https://github.com/docker/setup-buildx-action/commits/master/
    uses: docker/setup-buildx-action@0f069ddc17b8eb78586b08a7fe335fd54649e2d3

  - name: Set Environment variables
    run: |
      DOCKER_LAYERS_PATH="/tmp/.buildx-cache-${{ inputs.image-name }}"
      echo "DOCKER_LAYERS_PATH=${DOCKER_LAYERS_PATH}" >> $GITHUB_ENV
    shell: bash

    # See https://github.com/docker/build-push-action/issues/252#issuecomment-744400434
  - name: Cache Docker layers
    # See https://github.com/actions/cache/commits/main/
    uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
    with:
      path: ${{ env.DOCKER_LAYERS_PATH }}
      key: ${{ runner.os }}-buildx-${{ inputs.image-name }}-${{ github.sha }}
      restore-keys: ${{ runner.os }}-buildx-${{ inputs.image-name }}

  - name: Build and push Docker image
    # See https://github.com/docker/build-push-action/commits/master/
    uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
    with:
      context: ${{ inputs.docker-context }}
      file: ${{ inputs.docker-file }}
      push: true
      provenance: false
      tags: ${{ steps.meta.outputs.tags }}
      build-args: ${{ inputs.docker-args }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=local,src=${{ env.DOCKER_LAYERS_PATH }}
      cache-to: type=local,dest=${{ env.DOCKER_LAYERS_PATH }}-new

  - name: Move Docker layers cache
    run: |
      rm -rf ${{ env.DOCKER_LAYERS_PATH }}
      mv ${{ env.DOCKER_LAYERS_PATH }}-new ${{ env.DOCKER_LAYERS_PATH }}
    shell: bash

  - name: Run Trivy vulnerability scanner
    if: ${{ inputs.trivy == 'true' }}
    # See https://github.com/aquasecurity/trivy-action/commits/master/
    uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
    with:
      image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      format: json
      output: trivy-results.json

  - name: Convert Trivy JSON report into sarif
    if: ${{ inputs.trivy == 'true' }}
    run: |
      trivy convert --format sarif --output trivy-results.sarif trivy-results.json
      trivy convert --format table --output trivy-results.table trivy-results.json

      if [[ -s trivy-results.table ]]; then
        {
          echo "### Security Output"
          echo "<details><summary>Click to expand</summary>"
          echo ""
          echo '```markdown'
          cat trivy-results.table
          echo '```'
          echo "</details>"
        } >> $GITHUB_STEP_SUMMARY
      fi
    shell: bash

  - name: Upload Trivy scan results to GitHub Security tab
    if: ${{ inputs.trivy == 'true' }}
    # See https://github.com/github/codeql-action/commits/main/
    uses: github/codeql-action/upload-sarif@3d3d628990a5f99229dd9fa1821cc5a4f31b613b
    with:
      sarif_file: trivy-results.sarif
      category: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
