name: Install asdf tools

inputs:
  plugins:
    description: List of additional plugins (e.g., <plugin>=<url>)
    required: false
  context:
    description: Directory of the file .tool-versions located
    default: .
    required: false

runs:
  using: composite
  steps:
  - name: Install asdf
      # see https://github.com/asdf-vm/actions/commit/2368b9def7a1194d67ae0afd9cbbd01e15f658a0
    uses: asdf-vm/actions/setup@6278efebb38ae025cc91dd008910f549e775a8c8

  - name: Cache tools
      # see https://github.com/actions/cache/commit/69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
    uses: actions/cache@36f1e144e1c8edb0a652766b484448563d8baf46
    with:
      path: /home/runner/.asdf
      key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

  - name: Install asdf tools
    run: |
      cd ${{ inputs.context }}

      plugins_str=$'${{ inputs.plugins }}'
      plugins=(${plugins_str//$'\n'/ })

      for plugin in "${plugins[@]}"
      do
        readarray -d '=' -t keyurl <<< "$plugin"
        if (( ${#keyurl[@]} < 2 )); then
          continue
        fi

        asdf plugin-add ${keyurl[0]} ${keyurl[1]} || true
      done

      cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
      asdf plugin-update --all

      while read -r line; do
        # Skip empty lines or lines starting with comments (#)
        if [[ -n "$line" && ! "$line" =~ ^# ]]; then
          tool=$(echo "$line" | awk '{print $1}')
          version=$(echo "$line" | awk '{print $2}')

          echo "Installing $tool $version..."
          asdf install "$tool" "$version"
        fi
      done < .tool-versions

      asdf reshim
    shell: bash
