name: Install asdf tools

inputs:
  plugins:
    description: List of additional plugins (e.g., <plugin>=<url>)
    required: false
  context:
    description: Directory of the file .tool-versions located
    default: .
    required: false

runs:
  using: composite
  steps:
  - name: Install asdf
      # See https://github.com/asdf-vm/actions/commit/main/
    uses: asdf-vm/actions/setup@1bf052e01b498bba4f98e1bbb5c609bc212cf463

  - name: Cache tools
      # See https://github.com/actions/cache/commits/main/
    uses: actions/cache@36f1e144e1c8edb0a652766b484448563d8baf46
    with:
      path: /home/runner/.asdf
      key: ${{ runner.os }}-^0.16.0-${{ hashFiles('**/.tool-versions') }}

  - name: Install asdf tools
    run: |
      cd ${{ inputs.context }}

      plugins_str=$'${{ inputs.plugins }}'
      plugins=(${plugins_str//$'\n'/ })

      for plugin in "${plugins[@]}"
      do
        readarray -d '=' -t keyurl <<< "$plugin"
        if (( ${#keyurl[@]} < 2 )); then
          continue
        fi

        asdf plugin add ${keyurl[0]} ${keyurl[1]} || true
      done

      cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin add || true
      asdf plugin update --all

      while read -r line; do
        # Skip empty lines or lines starting with comments (#)
        if [[ -n "$line" && ! "$line" =~ ^# ]]; then
          tool=$(echo "$line" | awk '{print $1}')
          version=$(echo "$line" | awk '{print $2}')

          echo "Installing $tool $version..."
          asdf install "$tool" "$version"
        fi
      done < .tool-versions

      asdf reshim
    shell: bash
