name: Install asdf tools
description: Install asdf tools based on the .tool-versions file and additional plugins

inputs:
  version:
    description: The version of asdf
    default: v0.19.0
    required: false
  plugins:
    description: List of additional plugins (e.g., <plugin>=<url>, comma-separated)
    required: false
  context:
    description: Directory of the file .tool-versions located
    default: .
    required: false

runs:
  using: composite
  steps:
  - name: Install asdf
    run: bash "${{ github.action_path }}/../asdf-install/install.sh"
    shell: bash
    env:
      ASDF_VERSION: ${{ inputs.version }}

  - name: Cache tools
    # See https://github.com/actions/cache/commits/main/
    uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
    with:
      path: ~/.asdf
      key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}-${{ hashFiles('**/.tool-versions') }}

  - name: Install asdf tools
    run: bash "${{ github.action_path }}/install.sh"
    shell: bash
    env:
      ASDF_TOOLS_CONTEXT: ${{ inputs.context }}
      ASDF_EXTRA_PLUGINS: ${{ inputs.plugins }}
