name: Validate GitHub Actions

on:
  pull_request:
    paths:
    - .github/workflows/**
    - action.yml
    - '*/action.yml'
  push:
    branches:
    - main
    paths:
    - .github/workflows/**
    - action.yml
    - '*/action.yml'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: rhysd/actionlint@011a6d15e749bb3f2d771eed9c7aa0e7e3e10ee7
