name: Check code/commit conventions

on:
  push:
    branches:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Rerun Pre-Commit Hooks on CI
      uses: ./precommit
      with:
        commit-on-pr: 'false'
        commit-on-push: 'false'
