name: Check code/commit conventions

on:
  push:
    branches:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@v4

    - name: Setup Tools
      uses: ./asdf-tools

    - uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Rerun Pre-Commit Hooks on CI
      run: |
        pip install -r requirements.txt
        pre-commit run --all-files

  commitlint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v6
