name: Check code/commit conventions

on:
  push:
    branches:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Rerun Pre-Commit Hooks on CI
      uses: ./pre-commit
      with:
        commit-on-pr: 'false'
        commit-on-push: 'true'
