name: Check code/commit conventions

on:
  push:
    branches:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Rerun Pre-Commit Hooks on CI
      uses: ./precommit
      with:
        commit-on-pr: 'false'
        commit-on-push: 'true'
