name: Test action asdf-tools
on:
  pull_request:
    paths:
    - .github/workflows/test-asdf-tools.yml
    - asdf-tools/**
    - tests/fixtures/asdf-tools/**
  push:
    branches:
    - main
    paths:
    - .github/workflows/test-asdf-tools.yml
    - asdf-tools/**
    - tests/fixtures/asdf-tools/**
  workflow_dispatch:

jobs:
  asdf-tools-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux x64
          runner: ubuntu-24.04
        - name: macOS Intel
          runner: macos-13
        - name: macOS Apple Silicon
          runner: macos-14
    runs-on: ${{ matrix.platform.runner }}
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Install asdf tools in another directory
      uses: ./asdf-tools
      with:
        context: tests/fixtures/asdf-tools
        plugins: |
          mongodb=https://github.com/junminahn/asdf-mongodb.git
          docker-compose=https://github.com/virtualstaticvoid/asdf-docker-compose.git

    - name: Check Node.js version
      run: |
        node -v | grep -q "v24.15.0"
      working-directory: tests/fixtures/asdf-tools
